#!/usr/bin/env python3
"""Validate OSS community contribution surface artifacts and publish report."""

from __future__ import annotations

import json
from datetime import date, datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_JSON = ROOT / "antigravity" / "reports" / "community_surface_report.json"
REPORT_MD = ROOT / "antigravity" / "docs" / f"COMMUNITY_SURFACE_REPORT_{date.today().isoformat()}.md"

REQUIRED_FILES = [
    ROOT / "CONTRIBUTING.md",
    ROOT / ".github" / "ISSUE_TEMPLATE" / "bug_report.md",
    ROOT / ".github" / "ISSUE_TEMPLATE" / "feature_request.md",
    ROOT / ".github" / "ISSUE_TEMPLATE" / "security_report.md",
    ROOT / ".github" / "ISSUE_TEMPLATE" / "config.yml",
    ROOT / ".github" / "pull_request_template.md",
    ROOT / ".github" / "TOPICS.md",
]


def list_missing(paths: list[Path]) -> list[str]:
    return [path.as_posix() for path in paths if not path.exists()]


def extract_topics(path: Path) -> list[str]:
    if not path.exists():
        return []

    topics: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            topics.append(stripped[2:].strip())
    return topics


def has_readme_contrib_link(readme: Path) -> bool:
    if not readme.exists():
        return False

    content = readme.read_text(encoding="utf-8", errors="ignore").lower()
    return "contributing" in content and ".github/issue_template" in content


def render_markdown(payload: dict) -> str:
    lines = [
        "# Community Surface Report",
        "",
        f"> Timestamp: {payload['timestamp']}",
        f"> Status: {payload['status']}",
        "",
        "## Coverage",
        "",
        f"- Required files: {payload['required_total']}",
        f"- Existing files: {payload['required_present']}",
        f"- Missing files: {len(payload['missing_files'])}",
        f"- Topics count: {len(payload['topics'])}",
        f"- README contribution links: {payload['readme_has_links']}",
        "",
    ]

    if payload["missing_files"]:
        lines.extend(["## Missing Files", ""])
        for item in payload["missing_files"]:
            lines.append(f"- {item}")
        lines.append("")

    lines.extend(["## Topics", ""])
    for topic in payload["topics"]:
        lines.append(f"- {topic}")

    lines.extend(["", "Generated by: antigravity/scripts/validate_community_surface.py", ""])
    return "\n".join(lines)


def main() -> int:
    missing = list_missing(REQUIRED_FILES)
    topics = extract_topics(ROOT / ".github" / "TOPICS.md")
    readme_linked = has_readme_contrib_link(ROOT / "README.md")

    status = "PASS"
    warnings: list[str] = []

    if missing:
        status = "FAIL"
    if len(topics) < 5:
        warnings.append("Recommended to maintain at least 5 repository topics.")
    if not readme_linked:
        warnings.append("README should reference CONTRIBUTING and issue templates.")

    if status == "PASS" and warnings:
        status = "WARN"

    payload = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "required_total": len(REQUIRED_FILES),
        "required_present": len(REQUIRED_FILES) - len(missing),
        "missing_files": missing,
        "topics": topics,
        "readme_has_links": readme_linked,
        "warnings": warnings,
    }

    REPORT_JSON.parent.mkdir(parents=True, exist_ok=True)
    REPORT_MD.parent.mkdir(parents=True, exist_ok=True)
    REPORT_JSON.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    REPORT_MD.write_text(render_markdown(payload), encoding="utf-8")

    print(f"Community surface status: {status}")
    print(f"Report JSON: {REPORT_JSON}")
    print(f"Report MD: {REPORT_MD}")

    return 0 if status != "FAIL" else 1


if __name__ == "__main__":
    raise SystemExit(main())
